{{- if and .Values.auth.rbac.enabled (not .Values.auth.rbac.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "etcd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "etcd.name" . }}
    helm.sh/chart: {{ template "etcd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.auth.rbac.rootPassword }}
  etcd-root-password: {{ .Values.auth.rbac.rootPassword | b64enc | quote }}
  {{ else }}
  etcd-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
