apiVersion: v1
kind: Service
metadata:
  name: {{ template "etcd.fullname" . }}-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app.kubernetes.io/name: {{ template "etcd.name" . }}
    helm.sh/chart: {{ template "etcd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: client
    port: {{ .Values.service.port  }}
    targetPort: client
  - name: peer
    port: {{ .Values.service.peerPort  }}
    targetPort: peer
  selector:
    app.kubernetes.io/name: {{ template "etcd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
