apiVersion: v1
kind: Service
metadata:
  name: {{ template "etcd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "etcd.name" . }}
    helm.sh/chart: {{ template "etcd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: client
    port: {{ .Values.service.port  }}
    targetPort: client
    {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)) }}
    nodePort: {{ .Values.service.nodePort  }}
    {{- end }}
  - name: peer
    port: {{ .Values.service.peerPort  }}
    targetPort: peer
    {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.peerNodePort)) }}
    nodePort: {{ .Values.service.peerNodePort  }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "etcd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
